### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

In [ ]:
import numpy as np

1.Data Creation

In [ ]:
students=np.array(["Prasanth","Vijay","Yash","Rishab"])
subjects=np.array(["Maths","English","Science","Computer"])
marks=np.array([[90,91,96,70],
                [85,88,91,78],
                [95,97,99,81],
                [91,98,78,76]])
print(students)
print(subjects)
print(marks)
print("-"*50)

['Prasanth' 'Vijay' 'Yash' 'Rishab']
['Maths' 'English' 'Science' 'Computer']
[[90 91 96 70]
 [85 88 91 78]
 [95 97 99 81]
 [91 98 78 76]]
--------------------------------------------------


2.Data Exploration

In [ ]:
print("shape of marks:",marks.shape)
print("Size of marks:",marks.size)
print("Dimension of marks:",marks.ndim)
print("Datatype of marks:",marks.dtype)
print("-"*50)

shape of marks: (4, 4)
Size of marks: 16
Dimension of marks: 2
Datatype of marks: int64
--------------------------------------------------


3.Data Transformation

In [ ]:
reshaped_marks=marks.reshape(2,4,2)
print("Reshape of marks:\n",reshaped_marks)


Reshape of marks:
 [[[90 91]
  [96 70]
  [85 88]
  [91 78]]

 [[95 97]
  [99 81]
  [91 98]
  [78 76]]]


4.Data Combination

In [ ]:
new_student=np.array([[98,99,96,91]])
marks=np.vstack((marks,new_student))
students=np.append(students,"Dhoni")
print(marks)
print(students)

[[90 91 96 70]
 [85 88 91 78]
 [95 97 99 81]
 [91 98 78 76]
 [98 99 96 91]]
['Prasanth' 'Vijay' 'Yash' 'Rishab' 'Dhoni']


In [ ]:
new_subject=np.random.randint(80,100,5).reshape(5,1)
marks=np.hstack((marks,new_subject))
subjects=np.append(subjects,"Python")
print("Added new subject 'Computer':\n",marks)
print("-"*50)

Added new subject 'Computer':
 [[90 91 96 70 86]
 [85 88 91 78 89]
 [95 97 99 81 93]
 [91 98 78 76 92]
 [98 99 96 91 97]]
--------------------------------------------------


5.Data Modification

In [ ]:
#Updating Vijay's Science mark:
marks[1][2]=99
print(marks)

[[90 91 96 70 86]
 [85 88 99 78 89]
 [95 97 99 81 93]
 [91 98 78 76 92]
 [98 99 96 91 97]]


In [ ]:
#Removing one student and removing removed student marks:
index_to_remove = np.where(students == "Dhoni")[0][0]
students=np.delete(students,index_to_remove)
marks=np.delete(marks,index_to_remove,axis=0)
print(students)
print(marks)




['Prasanth' 'Vijay' 'Yash' 'Rishab']
[[90 91 96 70 86]
 [85 88 99 78 89]
 [95 97 99 81 93]
 [91 98 78 76 92]]


In [ ]:
#identifying unique marks:
unique_marks=np.unique(marks)
print(unique_marks)

[70 76 78 81 85 86 88 89 90 91 92 93 95 96 97 98 99]


6.Data Type Handling

In [ ]:
marks_float=marks.astype(dtype=float)
print(marks_float)
print(marks_float.dtype)

[[90. 91. 96. 70. 86.]
 [85. 88. 99. 78. 89.]
 [95. 97. 99. 81. 93.]
 [91. 98. 78. 76. 92.]]
float64


7.Copy and View Behaviour

In [ ]:
marks_copy=marks.copy()
marks_view=marks.view()
marks[1][0]=100
print(marks_copy)
print(marks_view)

[[90 91 96 70 86]
 [85 88 99 78 89]
 [95 97 99 81 93]
 [91 98 78 76 92]]
[[ 90  91  96  70  86]
 [100  88  99  78  89]
 [ 95  97  99  81  93]
 [ 91  98  78  76  92]]


Analysis examples

In [ ]:
average_per_student=marks.mean(axis=1)
average_per_subject=marks.mean(axis=0)
print(average_per_student)
print(average_per_subject)

[86.6 90.8 93.  87. ]
[94.   93.5  93.   76.25 90.  ]
